name: PyInstaller Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest 
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Miniconda with 64-bit Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: digestai
          python-version: ${{ matrix.python-version }}
      - name: Install Software Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pylint pytest
          pip install pyinstaller
          python -m pip check

      - name: Run PyInstaller
        run: pyinstaller main.spec

      - name: Verify executable creation
        run: dir dist\\digest.exe
        if: ${{ success() }}
        shell: cmd
